### ISSUE TITLE
Grant @benbalter, @parkr, and @jldec collab & rubygems push access

### ISSUE THREAD

**Issue by parkr** [gjtorikian/jekyll-html-pipeline#8]
Dearest @gjtorikian, in order that we may better assist you in maintaining this gem, please:

- [x] Grant @benbalter commit access
- [x] Grant @parkr commit access
- [x] Grant @jldec commit access
- [x] Grant @benbalter RubyGems.org push access (via `gem owner --add <rubygems_email>`)
- [x] Grant @parkr RubyGems.org push access (via `gem owner --add <rubygems_email>`)
- [ ] Grant @jldec RubyGems.org push access (via `gem owner --add <rubygems_email>`)

Blocks #7.

:sparkling_heart:

**Comment by gjtorikian** [comment]
What are your RubyGems emails?

**Comment by parkr** [comment]
@gjtorikian My personal gmail account. username + lastname @gmail.com

**Comment by gjtorikian** [comment]
Closing this still pending @jldec's RubyGems email. Two out of three ain't bad.
