### ISSUE TITLE
possible to access results from filters?

### ISSUE THREAD

**Issue by dmalan** [gjtorikian/jekyll-html-pipeline#9]
Most [html-pipeline](https://github.com/jch/html-pipeline/tree/master/lib/html/pipeline) filters simply transform their input into filtered output, but I noticed that the [`TableOfContentsFilter`](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb) also tucks the actual TOC (a nested unordered list) in a `result` hash, which is passed in as a third argument to [`call`](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline.rb#L89-L114). [Excerpt](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb#L33-L52) from the filter below. Is it possible to access that `result` hash via Jekyll, though, as in a template?

```ruby
def call
  result[:toc] = ""

  headers = Hash.new(0)
  doc.css('h1, h2, h3, h4, h5, h6').each do |node|
    text = node.text
    id = ascii_downcase(text)
    id.gsub!(PUNCTUATION_REGEXP, '') # remove punctuation
    id.gsub!(' ', '-') # replace spaces with dash

    uniq = (headers[id] > 0) ? "-#{headers[id]}" : ''
    headers[id] += 1
    if header_content = node.children.first
      result[:toc] << %Q{<li><a href="##{id}#{uniq}">#{text}</a></li>\n}
      header_content.add_previous_sibling(%Q{<a id="#{id}#{uniq}" class="anchor" href="##{id}#{uniq}" aria-hidden="true">#{anchor_icon}</a>})
    end
  end
  result[:toc] = %Q{<ul class="section-nav">\n#{result[:toc]}</ul>} unless result[:toc].empty?
  doc
end
```

We're currently invoking the filter via `_config.yml` with:

```
markdown: HTMLPipeline
html_pipeline:
  filters:
    - "markdownfilter"
    - "tableofcontentsfilter"
    - "autolinkfilter"
    - "rougefilter"
```

Thank you for the handy plugin!

**Comment by gjtorikian** [comment]
I believe you'll also want to use https://github.com/gjtorikian/page-toc-filter in conjunction, because at the time I couldn't find any other way to achieve this without messing with the official toc_filter. Does that help?

**Comment by dmalan** [comment]
Ah, thanks very much, sorry for the belated reply!
